import "~/styles/globals.css";

import type { Metadata } from "next";
import { Geist } from "next/font/google";

import { NavBar } from "~/app/_components/navbar";
import { TRPCReactProvider } from "~/trpc/react";

export const metadata: Metadata = {
	title: "Neon 0.1",
	description: "Generated by create-t3-app",
	icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const geist = Geist({
	subsets: ["latin"],
	variable: "--font-geist-sans",
});

export default function RootLayout({
	children,
}: Readonly<{ children: React.ReactNode }>) {
	return (
		<html lang="en" className={`${geist.variable}`}>
			<body>
				<div className="bg-background text-foreground">
					<TRPCReactProvider>
						{children}
						<NavBar />
					</TRPCReactProvider>
				</div>
			</body>
		</html>
	);
}
